### ISSUE TITLE
Why does this project use python 2?

### ISSUE THREAD

**Issue by konstin** [stadt-karlsruhe/geoextract#1]
Apparently, this project use python 2 instead of python 3 while importing the most important python 3 features through `__future__`. What is the reason for not using python 3 directly?

**Comment by torfsen** [comment]
Compatibility with legacy infrastructure, mostly. However, there shouldn't be a lot of hard dependencies on Python 2 (e.g. geoextract internally uses Unicode for everything), so making it compatible with Python 3 should be easy. Feel free to provide PRs or raise tickets for compatiblity issues.

**Comment by CatoTH** [comment]
I played around a bit, and yes, the changes necessary to make it work with python 3 seem to be rather simple: https://github.com/stadt-karlsruhe/geoextract/compare/master...CatoTH:python3?expand=1

**Comment by torfsen** [comment]
Thanks for the input, @CatoTH!

I've opened a separate ticket for actually implementing the Python 3 compatibility: #2. However, it's not our highest priority at the moment.

**Comment by torfsen** [comment]
Python version 3.4 and later are now supported (see #2).
