### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by konstin** [stadt-karlsruhe/geoextract#4]
This package should be published to [pypi](https://pypi.python.org/pypi) so it can be easily installed with pip.

**Comment by torfsen** [comment]
I agree that publishing the package on PyPI would be a good idea. Note, however, that pip can install directly from git repositories:

    pip install git+https://github.com/stadt-karlsruhe/geoextract.git

**Comment by konstin** [comment]
I already use pip with the git url, but it is tedious to use as pip is quite fragile with everything non-standart
